services:

  Mehdibo\Bundle\PasetoBundle\Services\LocalPasetoBuilder: "@mehdibo_paseto.local_builder"
  Mehdibo\Bundle\PasetoBundle\Services\PublicPasetoBuilder: "@mehdibo_paseto.public_builder"
  Mehdibo\Bundle\PasetoBundle\Services\LocalPasetoParser: "@mehdibo_paseto.local_parser"
  Mehdibo\Bundle\PasetoBundle\Services\PublicPasetoParser: "@mehdibo_paseto.public_parser"
  ParagonIE\Paseto\Keys\SymmetricKey: "@mehdibo_paseto.symmetric_key"
  ParagonIE\Paseto\Keys\AsymmetricSecretKey: "@mehdibo_paseto.asymmetric_secret_key"
  ParagonIE\Paseto\Keys\AsymmetricPublicKey: "@mehdibo_paseto.asymmetric_public_key"

  mehdibo_paseto.local_parser:
    class: Mehdibo\Bundle\PasetoBundle\Services\LocalPasetoParser
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\ParserFactory', 'localParser' ]
    arguments: ["@mehdibo_paseto.symmetric_key"]

  mehdibo_paseto.public_parser:
    class: Mehdibo\Bundle\PasetoBundle\Services\PublicPasetoParser
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\ParserFactory', 'publicParser' ]
    arguments: ["@mehdibo_paseto.asymmetric_public_key"]

  mehdibo_paseto.local_builder:
    class: Mehdibo\Bundle\PasetoBundle\Services\LocalPasetoBuilder
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\PasetoBuilderFactory', 'localPasetoFactory' ]
    arguments: ["@mehdibo_paseto.symmetric_key"]

  mehdibo_paseto.public_builder:
    class: Mehdibo\Bundle\PasetoBundle\Services\PublicPasetoBuilder
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\PasetoBuilderFactory', 'publicPasetoFactory' ]
    arguments: ["@mehdibo_paseto.asymmetric_secret_key"]

  mehdibo_paseto.symmetric_key:
    class: ParagonIE\Paseto\Keys\SymmetricKey
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\KeysFactory', 'symmetricKeyFactory' ]
    arguments: ["%mehdibo_paseto.secret_keys.symmetric_key%"]

  mehdibo_paseto.asymmetric_secret_key:
    class: ParagonIE\Paseto\Keys\AsymmetricSecretKey
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\KeysFactory', 'asymmetricSecretKeyFactory' ]
    arguments: ["%mehdibo_paseto.secret_keys.asymmetric_key%"]

  mehdibo_paseto.asymmetric_public_key:
    class: ParagonIE\Paseto\Keys\AsymmetricPublicKey
    factory: [ 'Mehdibo\Bundle\PasetoBundle\Factories\KeysFactory', 'asymmetricPublicKeyFactory' ]
    arguments: ["@mehdibo_paseto.asymmetric_secret_key"]

  Mehdibo\Bundle\PasetoBundle\Command\GenerateSymmetricKey:
    tags: ['console.command']

  Mehdibo\Bundle\PasetoBundle\Command\GenerateAsymmetricKey:
    tags: [ 'console.command' ]

  Mehdibo\Bundle\PasetoBundle\Command\GenerateToken:
    tags: [ 'console.command' ]
    arguments: ['@mehdibo_paseto.local_builder', '@mehdibo_paseto.public_builder']

  Mehdibo\Bundle\PasetoBundle\Command\DecodeToken:
    tags: [ 'console.command' ]
    arguments: [ '@mehdibo_paseto.local_parser', '@mehdibo_paseto.public_parser' ]
